name: PegasusAbilities
main: net.inkyquill.equestria.flight.PegasusAbilities
version: 0.1
commands:
  haste:
    description: Hastes user when flying.
  rainboom:
    description: More haste for flying creatures.
  flightadmin:
    description: Administrates flight regions.
    aliases: fa